config/routes.rb
Ipasa::Application.routes.draw do
  resources :photos

  resources :properties

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :descripcion, :property_id, :ruta
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :comentario, :direccion, :google, :locality_id, :nombre, :num_ext, :num_int, :precio, :status_oferta, :status_renta, :type_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ipasa</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :property_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :property_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :descripcion, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ruta, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :ruta, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                photos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<%- model_class = @photo.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/index.html.erb
<%- model_class = Photo.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:property_id) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:ruta) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to photo.id, photo_path(photo) %></td>
        <td><%= photo.property_id %></td>
        <td><%= photo.descripcion %></td>
        <td><%= photo.ruta %></td>
        <td><%=l photo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_photo_path(photo), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      photo_path(photo),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_photo_path,
            :class => 'btn btn-primary' %>

app/views/photos/new.html.erb
<%- model_class = @photo.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/show.html.erb
<%- model_class = @photo.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:property_id) %>:</strong></dt>
  <dd><%= @photo.property_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @photo.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ruta) %>:</strong></dt>
  <dd><%= @photo.ruta %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              photos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_photo_path(@photo), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              photo_path(@photo),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/properties/_form.html.erb
<%= form_for @property, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :num_int, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :num_int, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :num_ext, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :num_ext, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :direccion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :direccion, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :google, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :google, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status_renta, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :status_renta, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status_oferta, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :status_oferta, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comentario, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comentario, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :type_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :locality_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :locality_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :precio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :precio, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                properties_path, :class => 'btn' %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<%- model_class = @property.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/properties/index.html.erb
<%- model_class = Property.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:num_int) %></th>
      <th><%= model_class.human_attribute_name(:num_ext) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:google) %></th>
      <th><%= model_class.human_attribute_name(:status_renta) %></th>
      <th><%= model_class.human_attribute_name(:status_oferta) %></th>
      <th><%= model_class.human_attribute_name(:comentario) %></th>
      <th><%= model_class.human_attribute_name(:type_id) %></th>
      <th><%= model_class.human_attribute_name(:locality_id) %></th>
      <th><%= model_class.human_attribute_name(:precio) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= link_to property.id, property_path(property) %></td>
        <td><%= property.nombre %></td>
        <td><%= property.num_int %></td>
        <td><%= property.num_ext %></td>
        <td><%= property.direccion %></td>
        <td><%= property.google %></td>
        <td><%= property.status_renta %></td>
        <td><%= property.status_oferta %></td>
        <td><%= property.comentario %></td>
        <td><%= property.type_id %></td>
        <td><%= property.locality_id %></td>
        <td><%= property.precio %></td>
        <td><%=l property.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_property_path(property), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      property_path(property),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_property_path,
            :class => 'btn btn-primary' %>

app/views/properties/new.html.erb
<%- model_class = @property.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/properties/show.html.erb
<%- model_class = @property.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @property.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:num_int) %>:</strong></dt>
  <dd><%= @property.num_int %></dd>
  <dt><strong><%= model_class.human_attribute_name(:num_ext) %>:</strong></dt>
  <dd><%= @property.num_ext %></dd>
  <dt><strong><%= model_class.human_attribute_name(:direccion) %>:</strong></dt>
  <dd><%= @property.direccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:google) %>:</strong></dt>
  <dd><%= @property.google %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status_renta) %>:</strong></dt>
  <dd><%= @property.status_renta %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status_oferta) %>:</strong></dt>
  <dd><%= @property.status_oferta %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comentario) %>:</strong></dt>
  <dd><%= @property.comentario %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_id) %>:</strong></dt>
  <dd><%= @property.type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:locality_id) %>:</strong></dt>
  <dd><%= @property.locality_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precio) %>:</strong></dt>
  <dd><%= @property.precio %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              properties_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_property_path(@property), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              property_path(@property),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>